% iscounter(hero1,hero2).
% hero1 is a counter to hero2.
iscounter(kalea,layla).
iscounter(kalea,chang_e).
iscounter(obsidia,hayabusa).
iscounter(obsidia,freya).
iscounter(obsidia,lancelot).
iscounter(zetian,balmond).
iscounter(zetian,zilong).
iscounter(lukas,hanabi).
iscounter(lukas,ixia).
iscounter(suyou,ixia).
iscounter(suyou,xavier).
iscounter(zhuxin,popol_and_kupa).
iscounter(zhuxin,cyclops).
iscounter(chip,vexana).
iscounter(chip,layla).
iscounter(chip,ixia).
iscounter(cici,fredrinn).
iscounter(cici,minotaur).
iscounter(nolan,hanabi).
iscounter(nolan,eudora).
iscounter(ixia,fredrinn).
iscounter(ixia,bane).
iscounter(arlott,sun).
iscounter(arlott,zilong).
iscounter(novaria,eudora).
iscounter(novaria,odette).
iscounter(joy,xavier).
iscounter(joy,vexana).
iscounter(fredrinn,vale).
iscounter(fredrinn,eudora).
iscounter(julian,cecilion).
iscounter(julian,aldous).
iscounter(xavier,hanabi).
iscounter(xavier,faramis).
iscounter(melissa,sun).
iscounter(melissa,zilong).
iscounter(yin,layla).
iscounter(yin,cecilion).
iscounter(floryn,uranus).
iscounter(floryn,lolita).
iscounter(edith,zilong).
iscounter(edith,aulus).
iscounter(valentina,hanabi).
iscounter(valentina,faramis).
iscounter(aamon,xavier).
iscounter(aamon,cecilion).
iscounter(aulus,hanabi).
iscounter(aulus,yve).
iscounter(aulus,gord).
iscounter(natan,tigreal).
iscounter(natan,gatotkaca).
iscounter(phoveus,wanwan).
iscounter(phoveus,arlott).
iscounter(phoveus,chou).
iscounter(beatrix,hylos).
iscounter(beatrix,belerick).
iscounter(gloo,cecilion).
iscounter(gloo,chang_e).
iscounter(paquito,gord).
iscounter(paquito,layla).
iscounter(mathilda,gord).
iscounter(mathilda,vale).
iscounter(yve,fredrinn).
iscounter(yve,barats).
iscounter(yve,aulus).
iscounter(brody,aamon).
iscounter(brody,yin).
iscounter(barats,belerick).
iscounter(barats,lolita).
iscounter(khaleed,cyclops).
iscounter(khaleed,xavier).
iscounter(benedetta,jawhead).
iscounter(benedetta,guinevere).
iscounter(luo_yi,eudora).
iscounter(luo_yi,gord).
iscounter(yu_zhong,aulus).
iscounter(yu_zhong,zilong).
iscounter(popol_and_kupa,lesley).
iscounter(popol_and_kupa,brody).
iscounter(atlas,vexana).
iscounter(atlas,eudora).
iscounter(carmilla,dyrroth).
iscounter(carmilla,lapu_lapu).
iscounter(cecilion,balmond).
iscounter(cecilion,terizla).
iscounter(silvanna,layla).
iscounter(silvanna,valir).
iscounter(wanwan,fredrinn).
iscounter(wanwan,luo_yi).
iscounter(masha,ixia).
iscounter(masha,layla).
iscounter(baxia,chang_e).
iscounter(baxia,silvanna).
iscounter(lylia,carmilla).
iscounter(lylia,hylos).
iscounter(dyrroth,gord).
iscounter(dyrroth,hanabi).
iscounter(ling,layla).
iscounter(ling,hanabi).
iscounter(x_borg,terizla).
iscounter(x_borg,aulus).
iscounter(terizla,zilong).
iscounter(terizla,sun).
iscounter(esmeralda,akai).
iscounter(esmeralda,lolita).
iscounter(guinevere,zilong).
iscounter(guinevere,silvanna).
iscounter(granger,chang_e).
iscounter(granger,cecilion).
iscounter(khufra,joy).
iscounter(khufra,lancelot).
iscounter(badang,layla).
iscounter(badang,odette).
iscounter(faramis,saber).
iscounter(faramis,eudora).
iscounter(kadita,aurora).
iscounter(kadita,eudora).
iscounter(minsitthar,benedetta).
iscounter(minsitthar,arlott).
iscounter(harith,belerick).
iscounter(harith,johnson).
iscounter(thamuz,zilong).
iscounter(thamuz,sun).
iscounter(kimmy,granger).
iscounter(kimmy,cecilion).
iscounter(belerick,lancelot).
iscounter(belerick,ling).
iscounter(hanzo,layla).
iscounter(hanzo,ixia).
iscounter(hanzo,zhuxin).
iscounter(lunox,yve).
iscounter(lunox,lylia).
iscounter(leomord,odette).
iscounter(leomord,pharsa).
iscounter(leomord,yve).
iscounter(leomord,cecilion).
iscounter(vale,terizla).
iscounter(vale,hilda).
iscounter(claude,vexana).
iscounter(claude,floryn).
iscounter(aldous,zilong).
iscounter(aldous,leomord).
iscounter(selena,gord).
iscounter(selena,layla).
iscounter(kaja,fanny).
iscounter(kaja,lancelot).
iscounter(chang_e,eudora).
iscounter(chang_e,odette).
iscounter(hanabi,tigreal).
iscounter(hanabi,belerick).
iscounter(uranus,tigreal).
iscounter(uranus,franco).
iscounter(martis,layla).
iscounter(martis,odette).
iscounter(valir,balmond).
iscounter(valir,fredrinn).
iscounter(gusion,layla).
iscounter(gusion,hanabi).
iscounter(angela,uranus).
iscounter(angela,belerick).
iscounter(jawhead,eudora).
iscounter(jawhead,saber).
iscounter(lesley,gatotkaca).
iscounter(lesley,fredrinn).
iscounter(pharsa,layla).
iscounter(pharsa,hanabi).
iscounter(pharsa,xavier).
iscounter(helcurt,layla).
iscounter(helcurt,chang_e).
iscounter(helcurt,vale).
iscounter(zhask,aldous).
iscounter(zhask,paquito).
iscounter(hylos,layla).
iscounter(hylos,gord).
iscounter(diggie,atlas).
iscounter(diggie,lolita).
iscounter(lancelot,cecilion).
iscounter(lancelot,pharsa).
iscounter(odette,layla).
iscounter(odette,irithel).
iscounter(argus,gord).
iscounter(argus,aurora).
iscounter(grock,gord).
iscounter(grock,layla).
iscounter(irithel,miya).
iscounter(irithel,alpha).
iscounter(harley,ixia).
iscounter(harley,cecilion).
iscounter(gatotkaca,layla).
iscounter(gatotkaca,popol_and_kupa).
iscounter(karrie,tigreal).
iscounter(karrie,fredrinn).
iscounter(roger,granger).
iscounter(roger,odette).
iscounter(vexana,layla).
iscounter(vexana,irithel).
iscounter(vexana,xavier).
iscounter(lapu_lapu,layla).
iscounter(lapu_lapu,eudora).
iscounter(aurora,leomord).
iscounter(aurora,thamuz).
iscounter(aurora,terizla).
iscounter(hilda,zilong).
iscounter(hilda,layla).
iscounter(estes,valir).
iscounter(estes,alice).
iscounter(cyclops,terizla).
iscounter(cyclops,alpha).
iscounter(johnson,alucard).
iscounter(johnson,zilong).
iscounter(moskov,thamuz).
iscounter(moskov,balmond).
iscounter(yi_sun_shin,uranus).
iscounter(yi_sun_shin,terizla).
iscounter(ruby,aldous).
iscounter(ruby,guinevere).
iscounter(alpha,layla).
iscounter(alpha,ixia).
iscounter(sun,franco).
iscounter(sun,gatotkaca).
iscounter(chou,terizla).
iscounter(chou,alpha).
iscounter(kagura,layla).
iscounter(kagura,eudora).
iscounter(natalia,novaria).
iscounter(natalia,irithel).
iscounter(gord,barats).
iscounter(gord,fredrinn).
iscounter(freya,lesley).
iscounter(freya,ixia).
iscounter(hayabusa,chang_e).
iscounter(hayabusa,cecilion).
iscounter(lolita,kimmy).
iscounter(lolita,cyclops).
iscounter(minotaur,paquito).
iscounter(minotaur,julian).
iscounter(layla,tigreal).
iscounter(layla,belerick).
iscounter(fanny,irithel).
iscounter(fanny,karrie).
iscounter(zilong,lylia).
iscounter(zilong,layla).
iscounter(eudora,wanwan).
iscounter(eudora,moskov).
iscounter(rafaela,masha).
iscounter(rafaela,barats).
iscounter(clint,moskov).
iscounter(clint,miya).
iscounter(bruno,hanabi).
iscounter(bruno,miya).
iscounter(bane,hylos).
iscounter(bane,belerick).
iscounter(franco,vale).
iscounter(franco,estes).
iscounter(franco,layla).
iscounter(akai,eudora).
iscounter(akai,odette).
iscounter(karina,layla).
iscounter(karina,hanabi).
iscounter(alucard,harley).
iscounter(alucard,aamon).
iscounter(tigreal,zilong).
iscounter(tigreal,freya).
iscounter(nana,eudora).
iscounter(nana,kadita).
iscounter(alice,cecilion).
iscounter(alice,chang_e).
iscounter(saber,layla).
iscounter(saber,eudora).
iscounter(balmond,layla).
iscounter(balmond,eudora).
iscounter(miya,saber).
iscounter(miya,eudora).
iscounter(miya,sun).